function VarName2 = import_params(workbookFile,sheetName,startRow,endRow)
%IMPORT_PARAMS Import data from a spreadsheet
%   VarName2 = IMPORT_PARAMS(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as
%   column vectors.
%
%   VarName2 = IMPORT_PARAMS(FILE,SHEET) reads from the specified worksheet.
%
%   VarName2 = IMPORT_PARAMS(FILE,SHEET,STARTROW,ENDROW) reads from the
%   specified worksheet for the specified row interval(s). Specify STARTROW
%   and ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   VarName2 = import_params('import-sheet.xlsx','Import Sheet',1,20);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2016/11/12 15:07:15

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 1;
    endRow = 20;
end

%% Import the data
data = xlsread(workbookFile, sheetName, sprintf('B%d:B%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    tmpDataBlock = xlsread(workbookFile, sheetName, sprintf('B%d:B%d',startRow(block),endRow(block)));
    data = [data;tmpDataBlock]; %#ok<AGROW>
end

%% Allocate imported array to column variable names
VarName2 = data(:,1);

